name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: my-python-flask-service
  REGION: ${{ secrets.REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-actions-repo/my-image:latest .
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-actions-repo/my-image:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-actions-repo/my-image:latest \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
